### PR TITLE
Store segment alignment as a power of 2, and bump metadata version to 2

### PR DESCRIPTION
**Pull request by sbc100**
This is an ABI break so bump the metadata version to 2

### CODE REVIEW

**Comment by dschuff** [comment]
I think we've promised so far that the ABI is not stable, so we can probably just continue to call this ABI version 1?

**Comment by sbc100** [comment]
I'd link to bump it anyway, just for completeness.  And to see what it looks like to actual do the bump.

**Comment by dschuff** [comment]
I think whenever we do do a bump we should also make it clear in the repo versioning (e.g. put it in the commit summary, maybe a git tag too) so it's easy to find the spec for previous revisions in the history.

**Comment by dschuff** [comment]
let's go ahead and get this in now to ensure it makes the branch.

**Pull request merged**
